# Generated by Django 5.0.6 on 2024-06-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_usertasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTasks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
