# Generated by Django 5.0.6 on 2024-07-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_accommodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='category',
            field=models.CharField(choices=[('pousada', 'Pousada'), ('chale', 'Chalé'), ('apto', 'Apto'), ('casa', 'Casa'), ('quarto', 'Quarto')], default='pousada', max_length=50),
        ),
    ]
