# Generated by Django 5.0.6 on 2024-07-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_accommodation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='localization',
            field=models.TextField(default='Not specified', max_length=100),
        ),
    ]
