# Generated by Django 5.0.7 on 2024-07-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_user_managers_user_emergency_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='social_name',
        ),
    ]
